name: expense
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  auto_size_text: ^3.0.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_icons:
  android: true
  ios: false
  image_path_android: "assets/icon/app_icon.png"

